/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Algoritmos.RegresionP;
import Controlador.GestionCeldas;
import Controlador.GestionEncabezadoTabla;
import Entidades.RegresionPolinomial;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author PERSONAL
 */
public class frmRegresionPolinomial extends javax.swing.JFrame {

    
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    DefaultTableModel dtm3 = new DefaultTableModel();
    frmGrafico grafico;
    String titulos [] = {"xi", "yi"};
    String titulos1 [] = {"xi", "yi", "xi^2", "xi^3", "xi^4", "xi yi", "xi^2 yi", "(yi - y')^2", "(yi-a0-a1xi-a2xi^2)^2", "Pronostico Y", "Residuos"};
    String titulos2 [] = {"xi", "yi", "xi^2", "xi^3", "xi^4", "xi yi", "xi^2 yi", "(yi - y')^2", "(yi-a0-a1xi-a2xi^2)^2", "Pronostico Y", "Residuos"};
    
                
    public frmRegresionPolinomial() {
        initComponents();
        dtm.setColumnIdentifiers(titulos);
        jTable1.setModel(dtm);
        dtm2.setColumnIdentifiers(titulos1);
        jTable2.setModel(dtm2);
        dtm3.setColumnIdentifiers(titulos2);
        jTable3.setModel(dtm3);
        encabezadoTabla();        
    }
    public void celdasFondo(){
        for (int i = 0; i < titulos.length; i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(new GestionCeldas("numerico"));
        }
        for (int i = 0; i < titulos1.length; i++) {
            jTable2.getColumnModel().getColumn(i).setCellRenderer(new GestionCeldas("numerico"));
            jTable3.getColumnModel().getColumn(i).setCellRenderer(new GestionCeldas("numerico"));
        }        
    }
    
    public void encabezadoTabla(){
        //TABLA 1
        JTableHeader jtableHeader = jTable1.getTableHeader();
        jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
        jTable1.setTableHeader(jtableHeader);
        //TABLA 2
        JTableHeader jtableHeader1 = jTable2.getTableHeader();
        jtableHeader1.setDefaultRenderer(new GestionEncabezadoTabla());
        jTable2.setTableHeader(jtableHeader1);
        //TABLA 3
        JTableHeader jtableHeader2 = jTable3.getTableHeader();
        jtableHeader2.setDefaultRenderer(new GestionEncabezadoTabla());
        jTable3.setTableHeader(jtableHeader2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbEcuacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbMediaX = new javax.swing.JLabel();
        lbMediaY = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbErrorEstandar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbCDeterminacion = new javax.swing.JLabel();
        btnGrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Regresion Polinomica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 11, -1, -1));

        jLabel2.setText("Datos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 43, -1, -1));

        jLabel3.setText("x :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("y :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtX.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 67, -1));
        getContentPane().add(txtY, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 67, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jButton1.setText("Limpiar Todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 55, -1, -1));

        jLabel5.setText("Ecuacion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 79, -1, -1));
        getContentPane().add(lbEcuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 448, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setMinimumSize(new java.awt.Dimension(30, 20));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 160));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 590, 160));

        jLabel7.setText("Sumatoria :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 590, 50));

        jLabel8.setText("Media de x :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel9.setText("Media de y :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));
        getContentPane().add(lbMediaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 80, 10));
        getContentPane().add(lbMediaY, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, 10));

        jLabel10.setText("Error Estandar :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));
        getContentPane().add(lbErrorEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 130, 10));

        jLabel11.setText("Coeficiente de determinacion :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
        getContentPane().add(lbCDeterminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 10));

        btnGrafica.setText("Visualizar Grafica");
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        double x;
        double y;
        double x2;
        double x3;
        double x4;
        double xy;
        double x2y;
        double yY2 = 0;
        double ecuacion = 0;
        double pronosticoY = 0;
        double residuos = 0;
        try {
            int numCols = jTable1.getModel().getColumnCount();

            Object [] fila = new Object[numCols];
             RegresionPolinomial or;

             x = Double.parseDouble(txtX.getText());
             y = Double.parseDouble(txtY.getText());

             x2 = Math.pow(x, 2);
             x3 = Math.pow(x, 3);
             x4 = Math.pow(x, 4);
             xy = x * y;
             x2y= x2 * y;

             RegresionP.orp.add(or = new RegresionPolinomial(x, y, x2, x3, x4, xy, x2y, yY2,ecuacion, pronosticoY,residuos));
             fila[0] = txtX.getText();
             fila[1] = txtY.getText();
             dtm.addRow(fila);
             
             //((DefaultTableModel) jTable1.getModel()).addRow(fila);
             txtX.setText("");
             txtY.setText("");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos ");
        }	
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String fun = ""; 
        RegresionP.aplicarRegresion(RegresionP.orp);

         jTable2.setModel(RegresionP.MostrarRegresion(RegresionP.orp));
         
         dtm3.addRow(RegresionP.Sumatoria());
         jTable3.setModel(dtm3);
         lbMediaX.setText(String.valueOf(RegresionP.calcularMediaX(RegresionP.orp)));
         lbMediaY.setText(String.valueOf(RegresionP.calcularMediaY(RegresionP.orp)));

         double a0 = RegresionP.matrix[0][3];
         double a1 = RegresionP.matrix[1][3];
         double a2 = RegresionP.matrix[2][3];
         lbEcuacion.setText("y = (" + a0 + ") + (" + a1 + ")x + (" + a2 + ")x^2");
         
         if(a0<0){
             String s = "" + a0 ;
             fun =  a1+"*x"+s;
             //System.err.println(fun);
         }else{
             String s = "" + a0 ;
             fun =  a1+"*x+"+s;
             //System.err.println(fun);
         }
         
         double erSt = Math.sqrt(RegresionP.SumEcuacion(RegresionP.orp) / (RegresionP.orp.size()-2));
         lbErrorEstandar.setText(String.valueOf(erSt));
         double det = ((RegresionP.SumyY2(RegresionP.orp) - RegresionP.SumEcuacion(RegresionP.orp)) / RegresionP.SumyY2(RegresionP.orp));
         lbCDeterminacion.setText(String.valueOf(det));
         //grafico = new frmGrafico(fun);
         celdasFondo();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtX.setText("");
        txtY.setText("");
        lbMediaX.setText("");
        lbMediaY.setText("");
        lbEcuacion.setText("");
        lbCDeterminacion.setText("");
        lbErrorEstandar.setText("");
        for (int i = 0; i < jTable1.getRowCount(); i++) {
             ((DefaultTableModel) jTable1.getModel()).removeRow(i);
             i-=1;
        }
        for (int i = 0; i < jTable2.getRowCount(); i++) {
                 ((DefaultTableModel) jTable2.getModel()).removeRow(i);
                 i-=1;
        }
        for (int i = 0; i < jTable3.getRowCount(); i++) {
                 ((DefaultTableModel) jTable3.getModel()).removeRow(i);
                 i-=1;
        }
        RegresionP.orp.clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        grafico.show();
    }//GEN-LAST:event_btnGraficaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegresionPolinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegresionPolinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegresionPolinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegresionPolinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegresionPolinomial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGrafica;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbCDeterminacion;
    private javax.swing.JLabel lbEcuacion;
    private javax.swing.JLabel lbErrorEstandar;
    private javax.swing.JLabel lbMediaX;
    private javax.swing.JLabel lbMediaY;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables
}
