/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Algoritmos.RegresionL;
import Entidades.RegresionLineal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class frmRegresionLineal extends javax.swing.JFrame {

    
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    DefaultTableModel dtm3 = new DefaultTableModel();
    public frmRegresionLineal() {
        initComponents();
        String titulos [] = {"xi", "yi"};
        dtm.setColumnIdentifiers(titulos);
        jTable1.setModel(dtm);
        String titulos1 [] = {"xi", "yi", "xi^2", "xi yi", "(yi - y')^2", "(yi - a0 - a1xi)^2", "Pronostico Y", "Residuos"};
        dtm2.setColumnIdentifiers(titulos1);
        jTable2.setModel(dtm2);
        String titulos2 [] = {"xi", "yi", "xi^2", "xi yi", "(yi - y')^2", "(yi - a0 - a1xi)^2", "Pronostico Y", "Residuos"};
        dtm3.setColumnIdentifiers(titulos2);
        jTable3.setModel(dtm3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbEcuacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbMediaX = new javax.swing.JLabel();
        lbMediaY = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbErrorEstandar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbCDeterminacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Regresion Lineal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 11, -1, -1));

        jLabel2.setText("Datos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 43, -1, -1));

        jLabel3.setText("x :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("y :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 67, -1));
        getContentPane().add(txtY, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 67, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jButton1.setText("Limpiar Todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 55, -1, -1));

        jLabel5.setText("Ecuacion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 79, -1, -1));
        getContentPane().add(lbEcuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 448, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setMinimumSize(new java.awt.Dimension(30, 20));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 160));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "xi", "yi", "xi^2", "xi * yi", "(yi - y')^2", "(yi - a0 - a1xi)^2", "Pronostico Y", "Residuos"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 590, 160));

        jLabel7.setText("Sumatoria :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "xi", "yi", "xi^2", "xi * yi", "(yi - y')^2", "(yi - a0 - a1xi)^2", "Pronostico Y", "Residuos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 590, 50));

        jLabel8.setText("Media de x :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel9.setText("Media de y :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));
        getContentPane().add(lbMediaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 80, 10));
        getContentPane().add(lbMediaY, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, 10));

        jLabel10.setText("Error Estandar :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));
        getContentPane().add(lbErrorEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 130, 10));

        jLabel11.setText("Coeficiente de determinacion :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
        getContentPane().add(lbCDeterminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        double x;
        double y;
        double x2;
        double xy;
        double yY2 = 0;
        double ecuacion = 0;
        double pronosticoY = 0;
        double residuos = 0;
        try {
            int numCols = jTable1.getModel().getColumnCount();

            Object [] fila = new Object[numCols];
             RegresionLineal or;

             x = Double.parseDouble(txtX.getText());
             y = Double.parseDouble(txtY.getText());

             x2 = Math.pow(x, 2);
             xy = x * y;

             RegresionL.orl.add(or = new RegresionLineal(x, y, x2, xy,yY2,ecuacion, pronosticoY,residuos));
             fila[0] = txtX.getText();
             fila[1] = txtY.getText();
             dtm.addRow(fila);
             //((DefaultTableModel) jTable1.getModel()).addRow(fila);
             txtX.setText("");
             txtY.setText("");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos ");
        }	
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //int numCols = jTable1.getModel().getColumnCount();

         //String [] fila = new String[RegresionL.orl.size()-1]; 

         RegresionL.aplicarRegresion(RegresionL.orl);

         jTable2.setModel(RegresionL.MostrarRegresion(RegresionL.orl));
         
         dtm3.addRow(RegresionL.Sumatoria());
         jTable3.setModel(dtm3);
         lbMediaX.setText(String.valueOf(RegresionL.calcularMediaX(RegresionL.orl)));
         lbMediaY.setText(String.valueOf(RegresionL.calcularMediaY(RegresionL.orl)));

         double a0 = RegresionL.calcular_a0(RegresionL.orl);
         double a1 = RegresionL.calcular_a1(RegresionL.orl);
         lbEcuacion.setText("y = (" + a0 + ") + (" + a1 + ")x");
         double erSt = Math.sqrt(RegresionL.SumEcuacion(RegresionL.orl) / (RegresionL.orl.size()-2));
         lbErrorEstandar.setText(String.valueOf(erSt));
         double det = ((RegresionL.SumyY2(RegresionL.orl) - RegresionL.SumEcuacion(RegresionL.orl)) / RegresionL.SumyY2(RegresionL.orl));
         lbCDeterminacion.setText(String.valueOf(det));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtX.setText("");
        txtY.setText("");
        lbMediaX.setText("");
        lbMediaY.setText("");
        lbEcuacion.setText("");
        lbCDeterminacion.setText("");
        lbErrorEstandar.setText("");
        for (int i = 0; i < jTable1.getRowCount(); i++) {
             ((DefaultTableModel) jTable1.getModel()).removeRow(i);
             i-=1;
        }
        for (int i = 0; i < jTable2.getRowCount(); i++) {
                 ((DefaultTableModel) jTable2.getModel()).removeRow(i);
                 i-=1;
        }
        for (int i = 0; i < jTable3.getRowCount(); i++) {
                 ((DefaultTableModel) jTable3.getModel()).removeRow(i);
                 i-=1;
        }
        RegresionL.orl.clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegresionLineal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbCDeterminacion;
    private javax.swing.JLabel lbEcuacion;
    private javax.swing.JLabel lbErrorEstandar;
    private javax.swing.JLabel lbMediaX;
    private javax.swing.JLabel lbMediaY;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables
}
